M48
; DRILL file {KiCad 8.0.2} date 2024-05-10T16:31:35+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-10T16:31:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.251
%
G90
G05
T1
X94.0Y-51.8
X94.0Y-100.8
X152.0Y-51.8
X152.0Y-100.8
T2
X101.207Y-95.754
X112.637Y-95.754
M30
